# Generated by Django 5.0 on 2024-01-03 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-createdAt',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='valor')),
                ('createdAt', models.DateField()),
                ('orderdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.orderdetailsale', verbose_name='orderdetailsales')),
            ],
            options={
                'verbose_name': 'Utility',
                'verbose_name_plural': 'Utilities',
                'ordering': ('-createdAt',),
            },
        ),
    ]
