# Generated by Django 5.0.1 on 2024-01-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_order_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailsale',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='orderdetails',
            field=models.ManyToManyField(to='sales.orderdetailsale', verbose_name='orderdetailsales'),
        ),
    ]
