# Generated by Django 5.0.1 on 2024-05-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0008_alter_utility_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='numero')),
                ('client', models.CharField(max_length=100, verbose_name='señor')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total')),
                ('created_at', models.DateField(auto_now=True, verbose_name='fecha')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='actualizacion')),
                ('orders', models.ManyToManyField(to='sales.orderdetailsale', verbose_name='orders')),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
            },
        ),
    ]
