# Generated by Django 5.0 on 2023-12-19 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_product_cost_with_tax_alter_product_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='empresa')),
                ('url', models.SlugField()),
                ('address', models.CharField(max_length=100, null=True, verbose_name='ciudad')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='factura')),
                ('items', models.IntegerField(default=0, verbose_name='items')),
                ('createdAt', models.DateField(verbose_name='facturacion')),
                ('expirationAt', models.DateField(verbose_name='vencimiento')),
                ('is_credit', models.BooleanField(verbose_name='credito')),
                ('way_to_pay', models.CharField(choices=[('contado', 0), ('credito 15 dias', 15), ('credito 30 dias', 30), ('credito 40 dias', 40), ('credito 60 dias', 60)], default=('contado', 0), max_length=100, verbose_name='forma de pago')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.company', verbose_name='companies')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='cantidad')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='precio')),
                ('tax', models.FloatField(choices=[('19 %', 1.19), ('no aplica', 1.0)], default=0.0, verbose_name='iva')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.bill', verbose_name='orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='products')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
