# Generated by Django 5.0 on 2023-12-20 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_cost_with_tax_alter_product_tax'),
        ('provider', '0003_alter_bill_items_alter_bill_way_to_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='product'),
            preserve_default=False,
        ),
    ]
