# Generated by Django 5.0 on 2023-12-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_alter_company_address_alter_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='createdAt',
            field=models.DateField(default='2023-01-01', verbose_name='creado'),
            preserve_default=False,
        ),
    ]
