# Generated by Django 5.0 on 2023-12-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_order_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='items',
        ),
    ]
