# Generated by Django 5.0 on 2023-12-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0009_alter_bill_way_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='way_to_pay',
            field=models.IntegerField(choices=[(1, 'contado'), (2, 'credito')], default=(1, 'contado'), max_length=100, verbose_name='forma de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.FloatField(choices=[(1.19, '19 %'), (1.0, 'no aplica')], default=0.0, verbose_name='iva'),
        ),
    ]
