# Generated by Django 5.0 on 2023-12-21 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_cost_with_tax_alter_product_tax'),
        ('provider', '0010_alter_bill_way_to_pay_alter_order_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-createdAt'], 'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='cantidad')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='precio')),
                ('tax', models.FloatField(choices=[(1.19, '19 %'), (1.0, 'no aplica')], default=0.0, verbose_name='iva')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total')),
                ('createdAt', models.DateField(verbose_name='creado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'OrderDetail',
                'verbose_name_plural': 'OrderDetails',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_detail',
            field=models.ManyToManyField(to='provider.orderdetail', verbose_name='details'),
        ),
    ]
