# Generated by Django 5.0 on 2023-12-22 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0011_alter_bill_options_remove_order_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='provider.bill', verbose_name='bill'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
