# Generated by Django 5.0 on 2023-12-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_alter_orderdetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='impuesto'),
        ),
    ]
