# Generated by Django 5.0 on 2023-12-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0014_alter_bill_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='way_to_pay',
            field=models.IntegerField(choices=[(1, 'contado'), (2, 'credito')], default=(1, 'contado'), verbose_name='forma de pago'),
        ),
    ]
