# Generated by Django 5.0.1 on 2024-01-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0015_alter_bill_way_to_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='bill',
        ),
        migrations.AddField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='cancelado'),
        ),
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.ManyToManyField(to='provider.orderdetail', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='tax',
            field=models.FloatField(choices=[(1.19, '19 %')], default=(1.19, '19 %'), verbose_name='iva'),
        ),
    ]
