# Generated by Django 5.0.1 on 2024-05-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0016_remove_orderdetail_bill_bill_is_paid_bill_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
