# Generated by Django 5.0 on 2023-12-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='descripcion'),
        ),
    ]
