# Generated by Django 5.0 on 2024-01-03 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_provider_options'),
        ('sales', '0004_alter_utility_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='value')),
                ('way_to_pay', models.CharField(choices=[('e', 'efectivo'), ('n', 'nequi'), ('b', 'bancolombia'), ('bb', 'banco bogota'), ('bcs', 'caja social'), ('bd', 'davivienda')], default=('e', 'efectivo'), max_length=10, verbose_name='tipo pago')),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name='creado')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order', verbose_name='orders')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ('-createdAt',),
            },
        ),
    ]
