# Generated by Django 5.0 on 2024-01-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_bill'),
        ('sales', '0004_alter_utility_createdat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill',
            new_name='SalesBill',
        ),
        migrations.AlterModelOptions(
            name='salesbill',
            options={'ordering': ('-createdAt',), 'verbose_name': 'SalesBill', 'verbose_name_plural': 'SalesBills'},
        ),
    ]
