# Generated by Django 5.0.1 on 2024-01-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_rename_bill_salesbill_alter_salesbill_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='reference',
            field=models.CharField(default='2024-01-01', max_length=50, unique=True, verbose_name='referencia'),
            preserve_default=False,
        ),
    ]
