# Generated by Django 5.0 on 2023-12-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, unique=True, verbose_name='descripcion')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='codigo')),
                ('url', models.SlugField()),
                ('stock', models.IntegerField(default=0, verbose_name='disponible')),
                ('unit', models.CharField(choices=[('und', 'unidad'), ('kl', 'kilo'), ('mts', 'metro')], default=('und', 'unidad'), max_length=50, verbose_name='unidad')),
                ('tax', models.FloatField(choices=[('19 %', 1.19), ('no aplica', 1.0)], default=('19 %', 1.19), verbose_name='inpuesto')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='costo')),
                ('updatedAt', models.DateField(verbose_name='actualizacion')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
