# Generated by Django 5.0 on 2023-12-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_cost_with_tax_alter_product_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='inpuesto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('und', 'unidad'), ('kl', 'kilo'), ('mts', 'metro'), ('m2', 'metro cuadrado')], default=('und', 'unidad'), max_length=50, verbose_name='unidad'),
        ),
    ]
