# Generated by Django 5.0 on 2023-12-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_tax_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.FloatField(default=0.0, verbose_name='inpuesto'),
        ),
    ]
